### PR TITLE
Cache UserName and Domain to improve performance when creating new EcsDocument

### PR DESCRIPTION
**Pull request by achapla**
The **EcsTextFormatter** performs really slowly with the File sink in Serilog.

On my lower-end virtual machine, I performed the test cases below: I initialized Serilog with a simple configuration to sink logs in a file with different formatters:

1. CompactJsonFormatter
2. EcsTextFormatter

The CompactJsonFormatter took an average of **0.45 seconds** to write 12,000 log messages, while the EcsTextFormatter took **5.5 seconds**.

Surprisingly, through profiling, I found that _Environment.UserName_ and _Environment.UserDomainName_ were the hottest path in execution.

So I **cached those variables in a static field** and performed the same case, which brought down the time to **1 second**.

Overall, there will be a significant improvement in throughput.

### CODE REVIEW

**Review by Mpdreamz — APPROVED** [review]
LGTM thanks for catching this and addressing the open TODO!

**Comment by achapla** [comment]
> @achapla are you able to sign our CLA? https://www.elastic.co/contributor-agreement
> 
> That way I am allowed to merge this PR 😄

Before committing changes, I signed CLA but something must have gone wrong, so today again I signed it. Can you please confirm same?
Let me know if further actions are required from my end.

**Comment by Mpdreamz** [comment]
The commit is signed with your gmail account and the CLA with a yahoo email. 

Would you mind signing again with your gmail account so we can satisfy the machines? :smile:

**Comment by Mpdreamz** [comment]
Thanks again @achapla !

**Comment by achapla** [comment]
Thank you @Mpdreamz and the Elastic team for helping us create better software and your contributions to open source. Anyway, this was my first ever commit in open source, and I learned a lot. Next time, I will take care of the mistakes that happened during the PR.

**Comment by Mpdreamz** [comment]
Awesome @achapla :tada: ! First of many I hope!

FYI: There were no mistakes on this PR just necessary bureaucracy on our end :joy_cat:

**Pull request merged**
