### PR TITLE
Fix Dictionary properties issue

### PR DESCRIPTION
**Pull request by kuanpak**
* fix EcsTextFormatter cannot support Dictionary properties
* add new line after LogEvent's json serialization

### CODE REVIEW

**Comment by codebrain** [comment]
cla/check

**Comment by codebrain** [comment]
Hi @kuanpak - thank you, would you be able to sign our CLA so that we can consider this contribution: https://www.elastic.co/contributor-agreement

**Comment by kuanpak** [comment]
Hi Stuart,

Actually I signed the CLA already.

Jacky Chu

**Comment by olksdr** [comment]
@kuanpak could you, please, remove (squash) this commit 9519c19 in your history and force-push to this branch to overwrite the history? 
image

Since this commit was done without proper settings, it is most probably causing the problems, the our chek  cannot identify that this commit from you.

**Comment by kuanpak** [comment]
Done the rebase and force-pushed.

**Comment by olksdr** [comment]
@kuanpak thanks!  Everything looks great now

**Pull request merged**
