### PR TITLE
EcsLayout - Use LogEventInfo.Logger instead of hardcoded DefaultLogger

### LINKED ISSUE #55: [FEATURE] Unify NLog and Serilog ECS representations
Consider moving "common" code used by both Serilog and NLog into the Elastic.CommonSchema project, so that they are in sync. It will be interesting to see if this is inherently possible in all cases as the Elastic.CommonSchema project should not contain references to any logging libraries.

For example Serilog `CatchErrors` includes `StackTrace` for inner-exceptions But NLog `CatchError` does not (At the same time you can optimize Serilog to not allocate unnecessary Exception-List)

### LINKED ISSUE #56: [FEATURE] Use correct logger name
You should change this method:

```c#
		private static Log GetLog(LogEventInfo logEventInfo)
		{
			var log = new Log
			{
				Level = logEventInfo.Level.ToString(),
				Logger = SpecialKeys.DefaultLogger,
				Original = logEventInfo.Message
			};

			return log;
		}
```

Into this (Use `logEventInfo.Logger` instead of `SpecialKeys.DefaultLogger`):

```c#
		private static Log GetLog(LogEventInfo logEventInfo)
		{
			var log = new Log
			{
				Level = logEventInfo.Level.ToString(),
				Logger = logEventInfo.Logger,
				Original = logEventInfo.Message
			};

			return log;
		}
```

This will match the use of `sourceContext` for Serilog.

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #56

### CODE REVIEW

**Comment by codebrain** [comment]
cla/check

**Comment by snakefoot** [comment]
Have already signed it for a different repository in your care.


Guess you will fix the cla app


Sent from my Sony Xperia


---- Stuart Cam wrote ----


cla/check

**Comment by snakefoot** [comment]
@Mpdreamz Any chance of having this merged?

**Comment by snakefoot** [comment]
@codebrain Is there something I can do, so this can be merged?

**Comment by Mpdreamz** [comment]
@snakefoot will look at it this week to get it in. Thank you for the PR, sorry for the radio silence!

**Comment by Mpdreamz** [comment]
Hopefully my merge build will spin on CI. Will merge it in if so and passes.

THanks again @snakefoot 👍

**Comment by snakefoot** [comment]
@Mpdreamz All builds done by you or me says:

> githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)

**Comment by v1v** [comment]
Jenkins run the tests please

**Comment by snakefoot** [comment]
@v1v Thank you! Can you also do the magic on #76 and #75 ?

**Pull request merged**
