### PR TITLE
Feature/console example elasticsearchloggerprovider

### PR DESCRIPTION
**Pull request by sgryphon**
Add an example that uses Essential.LoggerProvider.Elasticsearch, a stand alone logger provider that uses ECS. (i.e. not part of a third party logging framework like Serilog or NLog that goes through a bridge/adapter, but a logger provider that connects directly to Microsoft.Extensions.Logging).

The example also includes a docker compose file to get Elasticsearch + Kibana up and running locally, and also demonstrates the use of the Microsoft LoggerMessage for high performance logging.

** NOTE: I am the author of the ElasticsearchLoggerProvider package. **

### CODE REVIEW

**Comment by sgryphon** [comment]
Have just signed the CLA. Thanks.

**Comment by Mpdreamz** [comment]
https://github.com/sgryphon/essential-logging/tree/master/src/Essential.LoggerProvider.Elasticsearch 

Looks amazing! What are your feelings towards getting that into this repository? 

I don't know how I feel accepting an example to a lib that's external to this repository. 

I would love to go all in on the whole thing or add a call out to your amazing work in our README. 

@russcam thoughts?

**Comment by sgryphon** [comment]
> https://github.com/sgryphon/essential-logging/tree/master/src/Essential.LoggerProvider.Elasticsearch
> Looks amazing! What are your feelings towards getting that into this repository?
> 

I would be more than happy to donate/migrate my code to the Elastic project, if you would like it. 

The current code is under LGPL, because I like to encourage open source, but happy to re-licence under Apache to be consistent with the rest of your project / sign over licence under your CLA to make it easier to manage.

If you are interested, I can merge across the code in a branch, and then update the assembly name to fit your project (Elastic.CommonSchema.LoggerProvider ?)

Once it is merged, I would put a note on the other project to refer to here.

**Comment by sgryphon** [comment]
Closing this as basically merged, with changes

**Pull request closed without merging**
