### PR TITLE
Access to log event during custom mapping

### PR DESCRIPTION
**Pull request by alaw-emoney**
* Ability to enrich the ECS from the log event
* This is a breaking change but not sure if anyone was using this

### CODE REVIEW

**Comment by alaw-emoney** [comment]
Would close issue #20

**Comment by codebrain** [comment]
Hi @alaw-emoney,

Thank you for your contribution, makes complete sense to pass the `LogEvent` to the Func. Would you mind signing our contributor agreement first, so that I am able to merge in this PR?

https://www.elastic.co/contributor-agreement

Thanks

**Comment by elasticcla** [comment]
Hi @alaw-emoney, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/ecs-dotnet/pull/19.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by alaw-emoney** [comment]
I have requested someone from eMoney sign the agreement for the whole company

**Comment by codebrain** [comment]
Hi @alaw-emoney - how are you getting on with the CLA signature? I was hoping to release a new package this week and would really like to include this PR change as I believe its very useful. Despite us being in pre-release I would prefer to limit the number of breaking changes if possible.

**Pull request closed without merging**
