### PR TITLE
NLog EcsLayout - Added support for Log Origin

### PR DESCRIPTION
**Pull request by snakefoot**
So you can do this:

```xml
<layout type="EcsLayout"
    logOriginCallSiteMethod="${callsite}"
    logOriginCallSiteFile="${callsite-filename}"
    logOriginCallSiteLine="${callsite-linenumber}"
 />
```

See also: https://github.com/NLog/NLog/wiki/Callsite-Layout-Renderer

Trying to fix one item from #77

### CODE REVIEW

**Comment by johnjaylward** [comment]
@snakefoot , I don't see the `${callsite-filename}` listed here: https://nlog-project.org/config/?tab=layout-renderers is it new for this request, or just in need of a documentation update?

**Comment by Mpdreamz** [comment]
@snakefoot this LGTM, are you able to ammend this PR with a test as well?

**Comment by snakefoot** [comment]
@Mpdreamz Added an unit-test that tries to capture Log-Origin on Exception.

**Comment by Mpdreamz** [comment]
Awesome, thank you @snakefoot really appreciated.

**Comment by Mpdreamz** [comment]
jenkins test this please

**Pull request merged**
