### PR TITLE
IncludeAspNetProperties property

### PR DESCRIPTION
**Pull request by michaelplavnik**
Resolves issue #296, by introducing IncludeAspNetProperties property to allow consumers to disable AspNet fields rendering. Extend support of AspNet fields rendering to NLog 4.7 (not only 5.0). AspNet related properties in EcsLayout class are not initialized in constructor as before, but in Initialize method.

### CODE REVIEW

**Comment by Mpdreamz** [comment]
@michaelplavnik thank you for signing the CLA however it needs to be done with your `user.email`. 

You can see the email you've used here: https://github.com/elastic/ecs-dotnet/pull/304.patch. 

Do you mind resigning the CLA with that email so I may review your PR ? :smile:

**Comment by michaelplavnik** [comment]
@Mpdreamz Signed with the mentioned email and with github email. Hope it helps, but I do not see an update on the page yet.

**Comment by michaelplavnik** [comment]
@Mpdreamz Thanks for your help. CLA signed!

**Comment by michaelplavnik** [comment]
@Mpdreamz There was a build timeout on windows pod. Could you please rerun windows pipeline?

**Comment by Mpdreamz** [comment]
@michaelplavnik I believe they are.

**Comment by Mpdreamz** [comment]
Thanks for seeing this one through while `main` was in flux! Looking to release this this week.

**Pull request merged**
