### PR TITLE
Rename _metadata to metadata for elastic purposes

### PR DESCRIPTION
**Pull request by kwsorensen**
Pull request made on behalf of https://github.com/elastic/ecs-dotnet/issues/104

### CODE REVIEW

**Comment by kwsorensen** [comment]
Can the maintainers here take a look at this?

**Comment by russcam** [comment]
jenkins run tests please

**Comment by russcam** [comment]
Thanks @kwsorensen 👍

**Comment by kwsorensen** [comment]
Give it a merge!

**Pull request merged**
