### PR TITLE
Bug fix - logger not including custom template & scope

### PR DESCRIPTION
**Pull request by sgryphon**
I noticed that the Microsoft.Extensions logger was no longer including the custom properties for MessageTemplate and Scopes.

Changes in Base meant I needed to implement the template method to explicitly add the additional properties.

This change is really only the last commit, and can be cherry picked to another branch if needed.

It was done on the Options Pattern branch because that is where I have a working example/test project. The other example project has hard coded to ipv4.fiddler:9200, which doesn't exist on my machine. On this branch tests default to the default install location localhost:5601, and can be overridden via properties, e.g. from command line.

This should be merged before releasing Extensions GA #95

### CODE REVIEW

**Comment by Mpdreamz** [comment]
@sgryphon mind rebasing this now that #107 made it in the main integration branch.

**Comment by sgryphon** [comment]
Good to go now

**Review by Mpdreamz — COMMENTED** [review]
Thank you for catching this! 

Is it worth implementing `TryRead` and `ReceiveProperty` to so that `LogEvent` property roundtrips during (de)serialization?

**Comment by russcam** [comment]
I added an additional test to assert that the `MessageTemplate` and `Scopes` properties are deserialized by the Elasticsearch client; they both need `[DataMember]` attributes for the client to deserialize correctly, as the client's internal serializer looks for camel case field names in JSON by default, and is strict about casing.

**Comment by russcam** [comment]
@sgryphon kicked off Jenkins to test in CI

**Comment by russcam** [comment]
@sgryphon CI is green- is this ready to be merged?

**Comment by sgryphon** [comment]
Yes, definitely. This one was actually a bug, so good to get it fixed.

Thanks for adding the help and adding the test (I think you added it).

Sly

**Pull request merged**
