### PR TITLE
Initial documentation for elastic.co

### PR DESCRIPTION
**Pull request by russcam**
Relates: #119

This commit adds initial documentation for the elastic.co website. It follows a similar layout and structure to the ECS logging documentation for Java.

### CODE REVIEW

**Review by Mpdreamz — APPROVED** [review]
LGTM! 👍 💯

**Comment by felixbarny** [comment]
I'm working on a general ECS logger overview page (https://github.com/elastic/ecs-logging/pull/37). Some of the info here and also on the Java docs overlap with that. Let's remove the overlapping parts so that they don't have to be repeated for each logger and discuss on https://github.com/elastic/ecs-logging/pull/37 how to best integrate or link to the general docs.

**Review by gregkalapos — APPROVED** [review]
LGTM.

At some point we should also add [Elasticsearch.Extensions.Logging](https://github.com/elastic/ecs-dotnet/tree/master/src/Elasticsearch.Extensions.Logging) to these docs.

**Comment by russcam** [comment]
> At some point we should also add `Elasticsearch.Extensions.Logging` to these docs.

💯 %! Intentionally left it out for now.

@felixbarny would it make sense to merge this in, and follow up with any overlapping changes? I've followed the tabbed approach of the ecs-logging-java for now, but I think the documentation might be clearer if there a separate "getting started" page for each ECS integration; each page would only have information relevant to that specific integration.

**Comment by felixbarny** [comment]
> each page would only have information relevant to that specific integration.

You mean a separate page for Serilog and NLog, for example? I like the compactness of the tabbed approach and that there's one page to link to for all loggers but we could try it out and see how it looks. However, I'd like all languages to follow a similar layout for the installation guide.

**Review by felixbarny — APPROVED** [review]

**Comment by russcam** [comment]
> You mean a separate page for Serilog and NLog, for example?

Yeah; each integration would be a subsection under "Getting started", so would still have a single reference URL for "getting started", but then would navigate to the subsection page relevant to the integration.

**Pull request merged**
