### PR TITLE
Public SerializerOptions

### PR DESCRIPTION
**Pull request by cwuethrich**
Allow to add a custom json converter.

#168

### CODE REVIEW

**Comment by cwuethrich** [comment]
@Mpdreamz is it possible to get this minimal change in?

**Review by Mpdreamz — APPROVED** [review]
LGTM!

**Comment by aheubusch** [comment]
I was about to ask for the same feature when I came across this PR. @cwuethrich @Mpdreamz The `JsonConfiguration` class is still `internal`.

**Pull request merged**
